<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Topographic Database • rgugik</title>
<!-- favicons --><link rel="icon" type="image/png" sizes="16x16" href="../favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="../favicon-32x32.png">
<link rel="apple-touch-icon" type="image/png" sizes="180x180" href="../apple-touch-icon.png">
<link rel="apple-touch-icon" type="image/png" sizes="120x120" href="../apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" type="image/png" sizes="76x76" href="../apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" type="image/png" sizes="60x60" href="../apple-touch-icon-60x60.png">
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha256-bZLfwXAP04zRMK2BjiO8iu9pf4FbLqX6zitd+tIvLhE=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Topographic Database">
<meta property="og:description" content="rgugik">
<meta property="og:image" content="/logo.png">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">rgugik</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.1.4</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/orthophotomap.html">Orthophotomap</a>
    </li>
    <li>
      <a href="../articles/DEM.html">Digital Elevation Model</a>
    </li>
    <li>
      <a href="../articles/topodb.html">Topographic Database</a>
    </li>
    <li>
      <a href="../articles/articles/geodb_description.html">General Geographic Database</a>
    </li>
  </ul>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/kadyb/rgugik/">
    <span class="fab fa fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="topodb_files/accessible-code-block-0.0.1/empty-anchor.js"></script><link href="topodb_files/anchor-sections-1.0/anchor-sections.css" rel="stylesheet">
<script src="topodb_files/anchor-sections-1.0/anchor-sections.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Topographic Database</h1>
                        <h4 class="author">Krzysztof Dyba, Jakub Nowosad</h4>
            
      
      <small class="dont-index">Source: <a href="https://github.com/kadyb/rgugik/blob/master/vignettes/topodb.Rmd"><code>vignettes/topodb.Rmd</code></a></small>
      <div class="hidden name"><code>topodb.Rmd</code></div>

    </div>

    
    
<style>
body {text-align: justify}
</style>
<div id="definition" class="section level2">
<h2 class="hasAnchor">
<a href="#definition" class="anchor"></a>Definition</h2>
<p><strong>Topographic Database</strong> (pl. <em>Baza Danych Obiektów Topograficznych</em>) is a vector (object) database containing the spatial location of topographic objects with their characteristics. The content and detail of the database correspond to the topographic map in the scale 1:10000. The thematic scope includes information on water network, communication network, land cover, buildings, technical structures, land use, protected areas, and territorial division units. The database is available in the Geography Markup Language (GML) format. The source of its data comes from:</p>
<ul>
<li>other spatial databases maintained by Polish Head Office of Geodesy and Cartography (e.g. <em>Register of Towns, Streets and Addresses</em>, <em>Register of Land and Buildings</em>, <em>State Register of Borders</em>),</li>
<li>databases maintained by other ministries or institutions (e.g., Ministry of Infrastructure, State Water Management, General Directorate for Environmental Protection),</li>
<li>fieldworks.</li>
</ul>
</div>
<div id="purpose" class="section level2">
<h2 class="hasAnchor">
<a href="#purpose" class="anchor"></a>Purpose</h2>
<p>The purpose of this vignette is to perform spatial operations on vector data from the Topographic Database. We focus on four cases, taking into account different types of geometry, i.e. point, line and polygon, and their attributes. In addition, we show how they can be visualized.</p>
</div>
<div id="analysis" class="section level2">
<h2 class="hasAnchor">
<a href="#analysis" class="anchor"></a>Analysis</h2>
<div class="sourceCode" id="cb1"><pre class="downlit">
<span class="co"># load packages</span>
<span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="kw"><a href="https://r-spatial.github.io/sf">sf</a></span>)
<span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="kw"><a href="https://kadyb.github.io/rgugik">rgugik</a></span>)
</pre></div>
<p>Our analysis area is the <em>bieszczadzki</em> county located in the Subcarpathian (<em>podkarpackie</em>) voivodeship. It is the farthest area in the south of Poland and has the lowest population density (19 people on km<sup>2</sup>).</p>
<div id="database" class="section level3">
<h3 class="hasAnchor">
<a href="#database" class="anchor"></a>Database</h3>
<p>We start by downloading the topographic database for our county using the <code><a href="../reference/topodb_download.html">topodb_download()</a></code> function.</p>
<div class="sourceCode" id="cb2"><pre class="downlit">
<span class="co"># 22.4 MB</span>
<span class="fu"><a href="../reference/topodb_download.html">topodb_download</a></span>(<span class="st">"bieszczadzki"</span>, outdir = <span class="st">"./data"</span>)
</pre></div>
<p>The downloaded database consists of many files in the <em>GML</em> format. All the data necessary for analyzes can be found in <code>data/PL.PZGiK.332.1801/BDOT10k/</code> location. A brief description of the structure of this database can be found <a href="https://kadyb.github.io/rgugik/articles/articles/geodb_description.html">here</a>.</p>
<p>First, let’s load the file with administrative units ( *PL.PZGiK.332.1801__OT_ADJA_A.xml* ), using the <strong>sf</strong> package and its <code><a href="https://rdrr.io/pkg/sf/man/st_read.html">read_sf()</a></code> function.</p>
<div class="sourceCode" id="cb3"><pre class="downlit">
<span class="kw">territory</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/sf/man/st_read.html">read_sf</a></span>(<span class="st">"data/PL.PZGiK.332.1801/BDOT10k/PL.PZGiK.332.1801__OT_ADJA_A.xml"</span>)
</pre></div>
<p>The file contains administrative units at various levels, let’s choose the lowest level, i.e. communes. There are three types of communes in this dataset: urban (<em>GM</em>), rural (<em>GW</em>), and urban-rural (<em>Gmw</em>). Their type is specified in the <code>rodzaj</code> column. Let’s select them.</p>
<div class="sourceCode" id="cb4"><pre class="downlit">
<span class="kw">communes</span> <span class="op">=</span> <span class="kw">territory</span>[<span class="kw">territory</span><span class="op">$</span><span class="kw">rodzaj</span> <span class="op">%in%</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"GM"</span>, <span class="st">"GW"</span>, <span class="st">"Gmw"</span>), <span class="st">"rodzaj"</span>]
<span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span>(<span class="kw">communes</span><span class="op">$</span><span class="kw">rodzaj</span>)
</pre></div>
<pre><code>## 
## Gmw  GW 
##   1   2</code></pre>
<p>We can see that the <em>bieszczadzki</em> county consists of two rural communes and one urban-rural commune. Let’s visualize it.</p>
<div class="sourceCode" id="cb6"><pre class="downlit">
<span class="fu"><a href="https://rdrr.io/pkg/sf/man/plot.html">plot</a></span>(<span class="kw">communes</span>, axes = <span class="fl">TRUE</span>, main = <span class="st">"Bieszczadzki county"</span>)
</pre></div>
<p><img src="topodb-communes-1.png"></p>
</div>
<div id="lengths-and-categories-of-roads" class="section level3">
<h3 class="hasAnchor">
<a href="#lengths-and-categories-of-roads" class="anchor"></a>Lengths and categories of roads</h3>
<p>In the first task, we calculate the lengths of roads taking into account their categories. Road data can be found in the *PL.PZGiK.332.1801__OT_SKDR_L.xml* file.</p>
<div class="sourceCode" id="cb7"><pre class="downlit">
<span class="kw">roads</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/sf/man/st_read.html">read_sf</a></span>(<span class="st">"data/PL.PZGiK.332.1801/BDOT10k/PL.PZGiK.332.1801__OT_SKDR_L.xml"</span>)
</pre></div>
<p>Let’s plot them. <!--JN: maybe it would be good to add a sentence or two of explanation of the following code --></p>
<div class="sourceCode" id="cb8"><pre class="downlit">
<span class="fu"><a href="https://rdrr.io/pkg/sf/man/plot.html">plot</a></span>(<span class="kw">roads</span>[<span class="st">"katZarzadzania"</span>], main = <span class="st">"Road category"</span>, reset = <span class="fl">FALSE</span>)
<span class="fu"><a href="https://rdrr.io/pkg/sf/man/plot.html">plot</a></span>(<span class="fu"><a href="https://rdrr.io/pkg/sf/man/st_geometry.html">st_geometry</a></span>(<span class="kw">territory</span>), add = <span class="fl">TRUE</span>)
</pre></div>
<p><img src="topodb-roads-1.png"></p>
<p>We have six road categories related to the managing entity, those are: national (K), voivodeship (W), county (P), communal (G), institutional (Z) and other (I).</p>
<p>We use the <code><a href="https://rdrr.io/pkg/sf/man/geos_measures.html">st_length()</a></code> function to find the length of each object in the table. Next, we create a data frame consisting of the road category and its length. Then we aggregate this data frame and calculate the sum of the lengths for each category.</p>
<div class="sourceCode" id="cb9"><pre class="downlit">
<span class="kw">length_roads</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/sf/man/geos_measures.html">st_length</a></span>(<span class="kw">roads</span>)
<span class="kw">length_roads</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span>(length = <span class="kw">length_roads</span>,
                          class = <span class="fu"><a href="https://rdrr.io/pkg/raster/man/factor.html">as.factor</a></span>(<span class="kw">roads</span><span class="op">$</span><span class="kw">katZarzadzania</span>))
<span class="kw">length_roads</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/sf/man/aggregate.sf.html">aggregate</a></span>(<span class="kw">length</span> <span class="op">~</span> <span class="kw">class</span>, data = <span class="kw">length_roads</span>, FUN = <span class="kw">sum</span>)
</pre></div>
<p>The results are given in meters - let’s convert them into kilometers.</p>
<div class="sourceCode" id="cb10"><pre class="downlit">
<span class="co"># convert to [km]</span>
<span class="kw">length_roads</span><span class="op">$</span><span class="kw">length</span> <span class="op">=</span> <span class="kw">units</span>::<span class="fu"><a href="https://rdrr.io/pkg/units/man/set_units.html">set_units</a></span>(<span class="kw">length_roads</span><span class="op">$</span><span class="kw">length</span>, <span class="st">"km"</span>)
</pre></div>
<p>Let’s also change the names of the categories.</p>
<div class="sourceCode" id="cb11"><pre class="downlit">
<span class="kw">road_class</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"communal"</span>, <span class="st">"other"</span>, <span class="st">"national"</span>, <span class="st">"county"</span>, <span class="st">"voivodeship"</span>,
               <span class="st">"institutional"</span>)
<span class="fu"><a href="https://rdrr.io/pkg/raster/man/factor.html">levels</a></span>(<span class="kw">length_roads</span><span class="op">$</span><span class="kw">class</span>) <span class="op">=</span> <span class="kw">road_class</span>
</pre></div>
<p>Now we can see the results. The <code>other</code> type of roads dominates that consists mainly of non-public roads.</p>
<div class="sourceCode" id="cb12"><pre class="downlit">
<span class="kw">length_roads</span>
</pre></div>
<pre><code>##           class          length
## 1      communal  186.17329 [km]
## 2         other 2819.55806 [km]
## 3      national   19.24996 [km]
## 4        county  187.17870 [km]
## 5   voivodeship  105.67567 [km]
## 6 institutional   10.44893 [km]</code></pre>
<p>We can also calculate the total length of the roads in this area.</p>
<div class="sourceCode" id="cb14"><pre class="downlit">
<span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>(<span class="kw">length_roads</span><span class="op">$</span><span class="kw">length</span>)
</pre></div>
<pre><code>## 3328.285 [km]</code></pre>
<p>The result is about 3328.285 km. Another aspect of the data that we can investigate is the density of the road network. We need to calculate the total area first, and then divide the total road length by the total area.</p>
<div class="sourceCode" id="cb16"><pre class="downlit">
<span class="kw">communes_area</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>(<span class="fu"><a href="https://rdrr.io/pkg/sf/man/geos_measures.html">st_area</a></span>(<span class="kw">communes</span>))
<span class="kw">communes_area</span> <span class="op">=</span> <span class="kw">units</span>::<span class="fu"><a href="https://rdrr.io/pkg/units/man/set_units.html">set_units</a></span>(<span class="kw">communes_area</span>, <span class="st">"km2"</span>)
<span class="kw">density</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>(<span class="kw">length_roads</span><span class="op">$</span><span class="kw">length</span>)<span class="op">/</span><span class="kw">communes_area</span>
<span class="kw">density</span> <span class="op">=</span> <span class="kw">units</span>::<span class="fu"><a href="https://rdrr.io/pkg/units/man/set_units.html">set_units</a></span>(<span class="kw">density</span>, <span class="st">"km/km2"</span>)
<span class="kw">density</span>
</pre></div>
<pre><code>## 2.921031 [km/km2]</code></pre>
<p>The road density is about 2.92 km/km<sup>2</sup>.</p>
</div>
<div id="roads-through-the-rivers" class="section level3">
<h3 class="hasAnchor">
<a href="#roads-through-the-rivers" class="anchor"></a>Roads through the rivers</h3>
<p>Another dataset included in the Topographic Database contains rivers for this area ( *PL.PZGiK.332.1801__OT_SWRS_L.xml* ).</p>
<div class="sourceCode" id="cb18"><pre class="downlit">
<span class="kw">rivers</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/sf/man/st_read.html">read_sf</a></span>(<span class="st">"data/PL.PZGiK.332.1801/BDOT10k/PL.PZGiK.332.1801__OT_SWRS_L.xml"</span>)
<span class="kw">rivers</span> <span class="op">=</span> <span class="kw">rivers</span>[<span class="kw">rivers</span><span class="op">$</span><span class="kw">rodzaj</span> <span class="op">==</span> <span class="st">"Rz"</span>, ] <span class="co"># select only rivers</span>
</pre></div>
<p>Rivers are divided into smaller sections with different parameters (such as, river width or data source). Let’s merge the same rivers into single feature (geometry) - we can use the attribute with ID (<code>idMPHP</code>) for that purpose. We can also give each river a category number by creating a sequence from 1 to n.</p>
<div class="sourceCode" id="cb19"><pre class="downlit">
<span class="kw">rivers</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/sf/man/aggregate.sf.html">aggregate</a></span>(<span class="kw">rivers</span>[, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"geometry"</span>, <span class="st">"idMPHP"</span>)],
                   <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span>(<span class="kw">rivers</span><span class="op">$</span><span class="kw">idMPHP</span>),
                   <span class="kw">sum</span>)
<span class="kw">rivers</span><span class="op">$</span><span class="kw">idMPHP</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq_len</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span>(<span class="fu"><a href="https://rdrr.io/pkg/raster/man/unique.html">unique</a></span>(<span class="kw">rivers</span><span class="op">$</span><span class="kw">idMPHP</span>)))
<span class="kw">rivers</span><span class="op">$</span><span class="kw">idMPHP</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/raster/man/factor.html">as.factor</a></span>(<span class="kw">rivers</span><span class="op">$</span><span class="kw">idMPHP</span>)
</pre></div>
<p>Let’s visualize the rivers’ courses.</p>
<div class="sourceCode" id="cb20"><pre class="downlit">
<span class="fu"><a href="https://rdrr.io/pkg/sf/man/plot.html">plot</a></span>(<span class="kw">rivers</span>[<span class="st">"idMPHP"</span>], main = <span class="st">"Rivers"</span>, reset = <span class="fl">FALSE</span>)
<span class="fu"><a href="https://rdrr.io/pkg/sf/man/plot.html">plot</a></span>(<span class="fu"><a href="https://rdrr.io/pkg/sf/man/st_geometry.html">st_geometry</a></span>(<span class="kw">territory</span>), add = <span class="fl">TRUE</span>)
</pre></div>
<p><img src="topodb-rivers-1.png"></p>
<p>With rivers and roads, we can designate points of intersection that symbolize bridges and crossings. We can use the <code><a href="https://rdrr.io/pkg/sf/man/geos_binary_ops.html">st_intersection()</a></code> function for this.</p>
<div class="sourceCode" id="cb21"><pre class="downlit">
<span class="kw">bridges</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/sf/man/st_geometry.html">st_geometry</a></span>(<span class="fu"><a href="https://rdrr.io/pkg/sf/man/geos_binary_ops.html">st_intersection</a></span>(<span class="kw">rivers</span>, <span class="kw">roads</span>))
<span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span>(<span class="kw">bridges</span>)
</pre></div>
<pre><code>## [1] 81</code></pre>
<p>We get 81 such points. Let’s plot them.</p>
<div class="sourceCode" id="cb23"><pre class="downlit">
<span class="fu"><a href="https://rdrr.io/pkg/sf/man/plot.html">plot</a></span>(<span class="fu"><a href="https://rdrr.io/pkg/sf/man/st_geometry.html">st_geometry</a></span>(<span class="kw">rivers</span>), main = <span class="st">"Bridges and crossings"</span>, col = <span class="st">"blue"</span>)
<span class="fu"><a href="https://rdrr.io/pkg/sf/man/plot.html">plot</a></span>(<span class="fu"><a href="https://rdrr.io/pkg/sf/man/st_geometry.html">st_geometry</a></span>(<span class="kw">territory</span>), add = <span class="fl">TRUE</span>)
<span class="fu"><a href="https://rdrr.io/pkg/sf/man/plot.html">plot</a></span>(<span class="kw">bridges</span>, add = <span class="fl">TRUE</span>, pch = <span class="fl">20</span>)
</pre></div>
<p><img src="topodb-bridges-1.png"></p>
</div>
<div id="land-cover" class="section level3">
<h3 class="hasAnchor">
<a href="#land-cover" class="anchor"></a>Land cover</h3>
<p>Let’s check the land cover data for our county - it is stored in files with the <code>PT</code> prefix. We use the <code><a href="https://rdrr.io/r/base/list.files.html">list.files()</a></code> function to list them. The <code>pattern</code> argument is important here, because it determines what files should be selected. Our <code>pattern</code> should look like this: <code>PT+.+A\\.xml$</code> - only files containing areal data (A) of land cover (PT) will be listed.</p>
<div class="sourceCode" id="cb24"><pre class="downlit">
<span class="kw">files</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.files.html">list.files</a></span>(<span class="st">"data/PL.PZGiK.332.1801/BDOT10k"</span>,
                   pattern = <span class="st">"PT+.+A\\.xml$"</span>,
                   full.names = <span class="fl">TRUE</span>)

<span class="co"># print filenames</span>
<span class="fu"><a href="https://rdrr.io/r/base/basename.html">basename</a></span>(<span class="kw">files</span>)
</pre></div>
<pre><code>##  [1] "PL.PZGiK.332.1801__OT_PTGN_A.xml"
##  [2] "PL.PZGiK.332.1801__OT_PTKM_A.xml"
##  [3] "PL.PZGiK.332.1801__OT_PTLZ_A.xml"
##  [4] "PL.PZGiK.332.1801__OT_PTNZ_A.xml"
##  [5] "PL.PZGiK.332.1801__OT_PTPL_A.xml"
##  [6] "PL.PZGiK.332.1801__OT_PTRK_A.xml"
##  [7] "PL.PZGiK.332.1801__OT_PTSO_A.xml"
##  [8] "PL.PZGiK.332.1801__OT_PTTR_A.xml"
##  [9] "PL.PZGiK.332.1801__OT_PTUT_A.xml"
## [10] "PL.PZGiK.332.1801__OT_PTWP_A.xml"
## [11] "PL.PZGiK.332.1801__OT_PTWZ_A.xml"
## [12] "PL.PZGiK.332.1801__OT_PTZB_A.xml"</code></pre>
<p>We also can exclude *PL.PZGiK.332.1801__OT_PTSO_A.xml* file from list, because this file contains zero objects (features).</p>
<div class="sourceCode" id="cb26"><pre class="downlit">
<span class="co"># drop "OT_PTSO_A.xml"</span>
<span class="kw">files</span> <span class="op">=</span> <span class="kw">files</span>[<span class="op">-</span><span class="fl">7</span>]
</pre></div>
<p>Let’s prepare the names of the objects to which the data will be loaded. <!--JN: I do not understand what do you mean here--> <!--JN: I understand the code, though.. Where did you get this names? Are they universal? This should be explained...--></p>
<div class="sourceCode" id="cb27"><pre class="downlit">
<span class="kw">layer_names</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"fallowlands"</span>, <span class="st">"communication"</span>, <span class="st">"forest"</span>, <span class="st">"undeveloped"</span>,
                <span class="st">"squares"</span>, <span class="st">"shrublands"</span>, <span class="st">"crops"</span>, <span class="st">"grassland"</span>,
                <span class="st">"water"</span>, <span class="st">"heaps"</span>, <span class="st">"buildings"</span>)
</pre></div>
<p>Now iteratively we will load each GML file, naming it from the list above. <!--JN: I would suggest rewriting the code in this section. I have almost never seen the use of assign in the exploratory code...--></p>
<div class="sourceCode" id="cb28"><pre class="downlit">
<span class="kw">layers</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span>(<span class="kw">files</span>, <span class="kw">read_sf</span>)
<span class="fu"><a href="https://rdrr.io/pkg/raster/man/names.html">names</a></span>(<span class="kw">layers</span>) <span class="op">=</span> <span class="kw">layer_names</span>
</pre></div>
<p>Previously, we used <code><a href="https://rdrr.io/pkg/sf/man/geos_measures.html">st_length()</a></code> to calculate the line length, now we use corresponding <code><a href="https://rdrr.io/pkg/sf/man/geos_measures.html">st_area()</a></code> function to calculate the area. For each object (layer), we calculate its area separately in a loop.</p>
<div class="sourceCode" id="cb29"><pre class="downlit">
<span class="co"># calculate areas in each layer</span>
<span class="kw">area_landcover</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span>(<span class="kw">layers</span>, <span class="kw">st_area</span>)
<span class="co"># sum areas for each layer</span>
<span class="kw">area_landcover</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">sapply</a></span>(<span class="kw">area_landcover</span>, <span class="kw">sum</span>)
<span class="co"># convert units</span>
<span class="kw">area_landcover</span> <span class="op">=</span> <span class="kw">units</span>::<span class="fu"><a href="https://rdrr.io/pkg/units/man/set_units.html">set_units</a></span>(<span class="kw">area_landcover</span>, <span class="st">"m^2"</span>)
<span class="kw">area_landcover</span> <span class="op">=</span> <span class="kw">units</span>::<span class="fu"><a href="https://rdrr.io/pkg/units/man/set_units.html">set_units</a></span>(<span class="kw">area_landcover</span>, <span class="st">"km^2"</span>)
<span class="fu"><a href="https://rdrr.io/pkg/raster/man/names.html">names</a></span>(<span class="kw">area_landcover</span>) <span class="op">=</span> <span class="kw">layer_names</span>
</pre></div>
<p>Let’s see the results (in kilometers).</p>
<div class="sourceCode" id="cb30"><pre class="downlit">
<span class="kw">area_landcover</span>
</pre></div>
<pre><code>## Units: [km^2]
##   fallowlands communication        forest   undeveloped       squares 
##    0.07561383    1.97014481  860.17248134    0.27817715    0.29038385 
##    shrublands         crops     grassland         water         heaps 
##    1.57266555  255.13528884    0.63447491    8.81181550    0.09220115 
##     buildings 
##   10.38781092</code></pre>
<p>Let’s make sure that the total land cover is equal to the area of our county. Some tiny precision differences are possible, so we should set the difference tolerance. This is possible using the <code><a href="https://rdrr.io/r/base/all.equal.html">all.equal()</a></code> function.</p>
<div class="sourceCode" id="cb32"><pre class="downlit">
<span class="fu"><a href="https://rdrr.io/r/base/all.equal.html">all.equal</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>(<span class="kw">area_landcover</span>), <span class="kw">communes_area</span>, tolerance = <span class="fl">0.001</span>)
</pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>Everything is correct. Let’s present the results as percentages of the area and sort them in the descending order.</p>
<div class="sourceCode" id="cb34"><pre class="downlit">
<span class="kw">landcover_percentage</span> <span class="op">=</span> <span class="kw">area_landcover</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>(<span class="kw">area_landcover</span>)<span class="op">*</span><span class="fl">100</span>
<span class="fu"><a href="https://rdrr.io/r/base/difftime.html">units</a></span>(<span class="kw">landcover_percentage</span>) <span class="op">=</span> <span class="kw">NULL</span> <span class="co"># drop units</span>
<span class="kw">landcover_percentage</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span>(<span class="kw">landcover_percentage</span>, <span class="fl">2</span>)
<span class="kw">landcover_percentage</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sort.html">sort</a></span>(<span class="kw">landcover_percentage</span>, decreasing = <span class="fl">TRUE</span>)
<span class="kw">landcover_percentage</span>
</pre></div>
<pre><code>##        forest         crops     buildings         water communication 
##         75.49         22.39          0.91          0.77          0.17 
##    shrublands     grassland       squares   undeveloped   fallowlands 
##          0.14          0.06          0.03          0.02          0.01 
##         heaps 
##          0.01</code></pre>
<p>Over 75% of the county’s area is covered by forests and only less than 1% by buildings.</p>
</div>
<div id="buffer" class="section level3">
<h3 class="hasAnchor">
<a href="#buffer" class="anchor"></a>Buffer</h3>
<p>In the last type of analysis in this vignette, we want to check how many buildings have access to bus stops within a given distance. We can apply spatial buffers to solve this question. Information about bus stops can be found in the *PL.PZGiK.332.1801__OT_OIKM_P.xml* file, where they have the <em>OIKM04</em> value in the <code>x_kod</code> attribute.</p>
<div class="sourceCode" id="cb36"><pre class="downlit">
<span class="kw">bus_stop</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/sf/man/st_read.html">read_sf</a></span>(<span class="st">"data/PL.PZGiK.332.1801/BDOT10k/PL.PZGiK.332.1801__OT_OIKM_P.xml"</span>)
<span class="kw">bus_stop</span> <span class="op">=</span> <span class="kw">bus_stop</span>[<span class="kw">bus_stop</span><span class="op">$</span><span class="kw">x_kod</span> <span class="op">==</span> <span class="st">"OIKM04"</span>, ]
</pre></div>
<p>Let’s prepare a visualization in which the bus stops is marked with blue dots and the buildings are presented as red polygons.</p>
<div class="sourceCode" id="cb37"><pre class="downlit">
<span class="kw">buildings</span> <span class="op">=</span> <span class="kw">layers</span><span class="op">$</span><span class="kw">buildings</span>
<span class="fu"><a href="https://rdrr.io/pkg/sf/man/plot.html">plot</a></span>(<span class="fu"><a href="https://rdrr.io/pkg/sf/man/st_geometry.html">st_geometry</a></span>(<span class="kw">communes</span>), main = <span class="st">"Bus stops"</span>)
<span class="fu"><a href="https://rdrr.io/pkg/sf/man/plot.html">plot</a></span>(<span class="fu"><a href="https://rdrr.io/pkg/sf/man/st_geometry.html">st_geometry</a></span>(<span class="kw">layers</span><span class="op">$</span><span class="kw">buildings</span>), add = <span class="fl">TRUE</span>, border = <span class="st">"red"</span>)
<span class="fu"><a href="https://rdrr.io/pkg/sf/man/plot.html">plot</a></span>(<span class="fu"><a href="https://rdrr.io/pkg/sf/man/st_geometry.html">st_geometry</a></span>(<span class="kw">bus_stop</span>), add = <span class="fl">TRUE</span>, pch = <span class="fl">20</span>, cex = <span class="fl">0.7</span>, col = <span class="st">"blue"</span>)
</pre></div>
<p><img src="topodb-busstops-1.png"></p>
<p>Let’s create a buffer for each bus stop with a range of 1 km using <code><a href="https://rdrr.io/pkg/sf/man/geos_unary.html">st_buffer()</a></code>.</p>
<div class="sourceCode" id="cb38"><pre class="downlit">
<span class="kw">bus_buffer</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/sf/man/geos_unary.html">st_buffer</a></span>(<span class="kw">bus_stop</span>, <span class="fl">1000</span>)
</pre></div>
<p>Now, we can plot it all.</p>
<div class="sourceCode" id="cb39"><pre class="downlit">
<span class="fu"><a href="https://rdrr.io/pkg/sf/man/plot.html">plot</a></span>(<span class="fu"><a href="https://rdrr.io/pkg/sf/man/st_geometry.html">st_geometry</a></span>(<span class="kw">communes</span>), main = <span class="st">"Bus stops buffers"</span>)
<span class="fu"><a href="https://rdrr.io/pkg/sf/man/plot.html">plot</a></span>(<span class="fu"><a href="https://rdrr.io/pkg/sf/man/st_geometry.html">st_geometry</a></span>(<span class="kw">buildings</span>), add = <span class="fl">TRUE</span>, border = <span class="st">"red"</span>)
<span class="fu"><a href="https://rdrr.io/pkg/sf/man/plot.html">plot</a></span>(<span class="fu"><a href="https://rdrr.io/pkg/sf/man/st_geometry.html">st_geometry</a></span>(<span class="kw">bus_buffer</span>), add = <span class="fl">TRUE</span>)
</pre></div>
<p><img src="topodb-buffers-1.png"></p>
<p>To return the buildings within the buffer range, we can perform the <code><a href="https://rdrr.io/pkg/sf/man/geos_binary_pred.html">st_within()</a></code> operation.</p>
<div class="sourceCode" id="cb40"><pre class="downlit">
<span class="kw">buildings_buffer</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/sf/man/geos_binary_pred.html">st_within</a></span>(<span class="kw">buildings</span>, <span class="kw">bus_buffer</span>)
</pre></div>
<p>The result is a nested list that consists of 2828 buildings and their associated buffers. Let’s count how many buildings are not in any buffer - function <code><a href="https://rdrr.io/r/base/lapply.html">sapply()</a></code> is useful for operations on lists.</p>
<div class="sourceCode" id="cb41"><pre class="downlit">
<span class="kw">buildings_ex</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">sapply</a></span>(<span class="kw">buildings_buffer</span>, <span class="kw">length</span>)
<span class="kw">buildings_ex</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span>(<span class="kw">buildings_ex</span> <span class="op">==</span> <span class="fl">0</span>)
<span class="kw">buildings_ex</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span>(<span class="kw">buildings_ex</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/pkg/raster/man/ncell.html">nrow</a></span>(<span class="kw">buildings</span>) <span class="op">*</span> <span class="fl">100</span>)
<span class="kw">buildings_ex</span>
</pre></div>
<pre><code>## [1] 14</code></pre>
<p>14% of the buildings in this county do not have access to a bus stop within 1 km radius.</p>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Krzysztof Dyba, Jakub Nowosad.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
